### ISSUE TITLE
Pantalla principal de requerimientos: formateo de decimales de % completitud

### ISSUE THREAD

**Issue by fdodino** [eschafir/tpi-audites-centralized#1]
Actualmente figura el progreso como "100.0" y está alineado a la izquierda, sería copado

* alinear a derecha el campo ya que es numérico
* utilizar un NumberFormat para que se vea "##0,00" o "##0"

**Comment by eschafir** [comment]
Se corrigio el formato del porcentaje, pero aun no puedo solucionar el tema de la alineacion del texto.
