### ISSUE TITLE
Hacer búsquedas filtrando valores en la base directamente - eliminar duplicados en la búsqueda

### ISSUE THREAD

**Issue by fdodino** [eschafir/tpi-audites-centralized#3]
Hoy se está buscando mediante un allInstances, con lo cual se hace una bajada de los datos y luego en memoria se filtra. Además se llaman a varios métodos search que hacen prácticamente lo mismo. Se puede unificar todo en un único searchByExample donde se pasa un  objeto revisión prototípico que puede tener

* name = el nombre a buscar (por ilike)
* archived = si incluye las revisiones archivadas

En ese caso el RepoRevisions debería considerar aquellos name != null para hacerr una búsqueda que contenga el nombre ingresado, y adicionalmente si archived = false debería filtrar aquellas revisiones que no estén archivadas, en caso contrario no aplicar ningún filtro (con lo cual traería a todas las revisiones)

**Comment by eschafir** [comment]
Se corrigio el bug

**Comment by fdodino** [comment]
Hola Esteban
       No cierres los issues, marcamos con el label Done, yo en la entrega
siguiente las cierro.
Saludos y suerte
Fernando

**Comment by eschafir** [comment]
Ahhh ok, perfecto!

Disculpa!

Abrazo!

2017-05-08 22:42 GMT-03:00 Fernando Dodino <notifications@github.com>:

> Hola Esteban
> No cierres los issues, marcamos con el label Done, yo en la entrega
> siguiente las cierro.
> Saludos y suerte
> Fernando
>
